import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AppChrome from "@/components/AppChrome";
import CookieConsent from "@/components/CookieConsent";
import AuthProvider from "@/components/AuthProvider";
import RequireAuthModal from "@/components/RequireAuthModal";
import { AuthModalProvider } from "@/contexts/AuthModalContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full bg-background">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-full text-foreground`}
      >
        <AuthProvider>
          <AuthModalProvider>
            <RequireAuthModal
              protectedPaths={["/contacts", "/my-cards", "/event"]}
            >
              <AppChrome>{children}</AppChrome>
            </RequireAuthModal>
            <CookieConsent />
          </AuthModalProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
